# Generated by Django 3.0.4 on 2020-05-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryList_lite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmationLink',
            field=models.CharField(default='Pass', max_length=200),
            preserve_default=False,
        ),
    ]
